### ISSUE TITLE
Example config file error: "AttributeError: module 'identity.config' has no attribute"

### ISSUE THREAD

**Issue by mrjones-plip** [synshop/ShopIdentifyer#55]
When trying to get my dev env set up, I got errors like this:

```
(.venv) mrjones@shopid:~/ShopIdentifyer$ ./localserver.py 
WARNING: Running in dev mode
You are running in development mode, but don't have the "ENCRYPTION_KEY" environment variable set so I will ask you for the password
You can save yourself some time by setting this environment variable
Please enter the enryption key to unlock this application: 
Traceback (most recent call last):
  File "/home/mrjones/ShopIdentifyer/./localserver.py", line 3, in <module>
    from identity import app
  File "/home/mrjones/ShopIdentifyer/identity/__init__.py", line 48, in <module>
    app.config['STRIPE_CACHE_REFRESH_CRON'] = config.STRIPE_CACHE_REFRESH_CRON
AttributeError: module 'identity.config' has no attribute 'STRIPE_CACHE_REFRESH_CRON'. Did you mean: 'STRIPE_CACHE_REFRESH_MINUTES'?
```

and:

```
WARNING: Running in dev mode
You are running in development mode, but don't have the "ENCRYPTION_KEY" environment variable set so I will ask you for the password
You can save yourself some time by setting this environment variable
Please enter the enryption key to unlock this application: 
Traceback (most recent call last):
  File "/home/mrjones/ShopIdentifyer/./localserver.py", line 3, in <module>
    from identity import app
  File "/home/mrjones/ShopIdentifyer/identity/__init__.py", line 50, in <module>
    app.config['STRIPE_CACHE_REBUILD_CRON'] = config.STRIPE_CACHE_REBUILD_CRON
AttributeError: module 'identity.config' has no attribute 'STRIPE_CACHE_REBUILD_CRON'. Did you mean: 'STRIPE_CACHE_REFRESH_CRON'?
```

We should update the example config to have all the required values.  As well, we should consider documenting what they all do

**Comment by mrjones-plip** [comment]
Testing it looks like these are the missing vars:

* ENCRYPTED_SMTP_USERNAME 
* ENCRYPTED_SMTP_PASSWORD 
* ENCRYPTED_DISCORD_BOT_TOKEN 
* DISCORD_MANAGE_ROLES 
* DISCORD_GUILD_ID 
* DISCORD_ROLE_PAID_MEMBER 
* DISCORD_ROLE_VETTED_MEMBER 
* SMTP_SERVER 
* SMTP_PORT 
* STRIPE_CACHE_REFRESH_CRON
* STRIPE_CACHE_REBUILD_CRON 
* STRIPE_CACHE_DEACTIVATE_CRON
