### ISSUE TITLE
Wrong password error: UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by mrjones-plip** [synshop/ShopIdentifyer#57]
When you start the app and use the wrong password, it is not clear what the problem is:

```
(.venv) mrjones@shopid:~/ShopIdentifyer$ ./localserver.py 
WARNING: Running in dev mode
You are running in development mode, but don't have the "ENCRYPTION_KEY" environment variable set so I will ask you for the password
You can save yourself some time by setting this environment variable
Please enter the enryption key to unlock this application: 
Traceback (most recent call last):
  File "/home/mrjones/ShopIdentifyer/./localserver.py", line 3, in <module>
    from identity import app
  File "/home/mrjones/ShopIdentifyer/identity/__init__.py", line 43, in <module>
    app.secret_key = CryptoUtil.decrypt(config.ENCRYPTED_SESSION_KEY,ENCRYPTION_KEY)
  File "/home/mrjones/ShopIdentifyer/identity/crypto/CryptoUtil.py", line 23, in decrypt
    plaintext = _unpad(padplain)
  File "/home/mrjones/ShopIdentifyer/identity/crypto/CryptoUtil.py", line 41, in _unpad
    vald = val.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 1: invalid continuation byte
```

Instead, we should tell the user the entered the wrong password

**Comment by mrjones-plip** [comment]
oop! When we merge in #52 , this looks OK:

```
(.venv) mrjones@shopid:~/ShopIdentifyer$ ./localserver.py 
WARNING: Running in dev mode
You are running in development mode, but don't have the "ENCRYPTION_KEY" environment variable set so I will ask you for the password
You can save yourself some time by setting this environment variable
Please enter the enryption key to unlock this application: 
ERROR Failed to decrypt "ENCRYPTED_" config variables in "config.py".  Error was: 'utf-8' codec can't decode byte 0x9e in position 1: invalid start byte
```

Closing this issue as that's a close enough error to help the user.
