### ISSUE TITLE
No DB docs results in: OperationalError  MySQLdb.OperationalError: (1698, "Access denied for user 'root'@'localhost'")

### ISSUE THREAD

**Issue by mrjones-plip** [synshop/ShopIdentifyer#58]
The [readme](https://github.com/synshop/ShopIdentifyer/blob/prod/README.md) has no info on how to set up the database.  With out this, after you launch the app you get an error in the browser:

```
OperationalError

MySQLdb.OperationalError: (1698, "Access denied for user 'root'@'localhost'")

Traceback (most recent call last):
  File "/home/mrjones/ShopIdentifyer/.venv/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mrjones/ShopIdentifyer/.venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/mrjones/ShopIdentifyer/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mrjones/ShopIdentifyer/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mrjones/ShopIdentifyer/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mrjones/ShopIdentifyer/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
```

We should add set up info for the DB to the docs, as well as consider checking for a valid connection on startup to output an error in the logs

**Comment by mrjones-plip** [comment]
It looks like there's [a sql directory](https://github.com/synshop/ShopIdentifyer/tree/prod/sql) that has a `create.sql` [file](https://github.com/synshop/ShopIdentifyer/blob/prod/sql/create.sql) which likely has what we need to bootstrap the DB.
